tasks:
  - name: Install
    command: |
      yarn install 
      sudo apt install mc tmux fonts-firacode fonts-powerline -y 
      sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      alias ztheme='(){ export ZSH_THEME="$@" && source $ZSH/oh-my-zsh.sh }'
      ztheme bira
      clear

  - init: yarn
    command: |
      cd web3dev-Solidity_And_Smart_Contracts
      yarn      
      
    openMode: split-right
    
ports:
  - port: 3000
    onOpen: ignore
    
  - port: 3333
    onOpen: ignore
