tasks:
  - name: First Running boot ;)
    init: >
      cd meu-portal-tchauzinho &&
      yarn --emoji true &&
      echo "------------------------------------------------------" &&
      echo "Fim script boot ;)" &&
      echo "------------------------------------------------------" &&
      gp sync-done bundle
        
#     command: |
#       clear    
#       echo "------------------------------------------------------"
#       pwd
#       echo "------------------------------------------------------"
#       cd meu-portal-tchauzinho
#       yarn --emoji true
#       echo "------------------------------------------------------"
#       echo "Fim script boot ;)"
#       echo "------------------------------------------------------"
    openMode: split-right
    
  - name: npx hardhat node server 
    init: gp sync-await bundle # wait for the above 'init' to finish
    command: |
      cd meu-portal-tchauzinho    
      clear    
      npx hardhat node          
    openMode: split-right
    
ports:
  - port: 3000, 8545
    onOpen: ignore
    
  - port: 3333
    onOpen: ignore
    
    

# sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"
# yarn --emoji true 2> >(grep -v warning 1>&2)
