tasks:
  - name: First Running boot ;)
    command:
      cd web3dev-Solidity_And_Smart_Contracts && yarn 
      sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"
      echo "Rodei 1ยบ ;)"
      
    openMode: split-right
    
ports:
  - port: 3000
    onOpen: ignore
    
  - port: 3333
    onOpen: ignore

# sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sed 's:env zsh::g' | sed 's:chsh -s .*$::g')"
# curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh &&
# sed -i.tmp 's:env zsh::g' install.sh &&
# sed -i.tmp 's:chsh -s .*$::g' install.sh &&
# sh install.sh &&
