tasks:
  - name: First Running boot ;)
    command: |
      echo "------------------------------------------------------"
      pwd
      echo "------------------------------------------------------"
      cd meu-portal-tchauzinho
      yarn
      echo "------------------------------------------------------"
      echo "Fim script boot ;)"
      echo "------------------------------------------------------"
      
      
    openMode: split-right
    
ports:
  - port: 3000
    onOpen: ignore
    
  - port: 3333
    onOpen: ignore

# sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"
