tasks:
  - name: Install
    init: >      
      sudo apt install mc tmux fonts-firacode fonts-powerline -y &&
      gp sync-done bundle # 'bundle' is an arbitrary name
    openMode: split-right     

  - name: Install 2 
    init: gp sync-await bundle
    command: |
      cd web3dev-Solidity_And_Smart_Contracts 
      yarn
      sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"      
    openMode: split-right
      
  - name: Install 3
    init: gp sync-await bundle
    command: |
      alias ztheme='(){ export ZSH_THEME="$@" && source $ZSH/oh-my-zsh.sh }'
      ztheme bira
      clear
    openMode: split-right
    
ports:
  - port: 3000
    onOpen: ignore
    
  - port: 3333
    onOpen: ignore

# sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sed 's:env zsh::g' | sed 's:chsh -s .*$::g')"
# curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh &&
# sed -i.tmp 's:env zsh::g' install.sh &&
# sed -i.tmp 's:chsh -s .*$::g' install.sh &&
# sh install.sh &&
