tasks:
  - name: First Running boot ;)
    init: >
      cd meu-portal-tchauzinho &&
      yarn --emoji true &&
      echo "------------------------------------------------------" &&
      echo "Fim script boot ;)" &&
      echo "------------------------------------------------------" &&
      gp sync-done bundle
    openMode: split-right
    
  - name: npx hardhat node server 
    init: gp sync-await bundle # wait for the above 'init' to finish
    command: |
      eval $(command gp env -e)
      cd meu-portal-tchauzinho    
      clear    
      npx hardhat node          
    
ports:
  - port: 3000-8545
    onOpen: ignore
    
  - port: 3333
    onOpen: ignore
    
    
#     command: |
#       clear    
#       echo "------------------------------------------------------"
#       pwd
#       echo "------------------------------------------------------"
#       cd meu-portal-tchauzinho
#       yarn --emoji true
#       echo "------------------------------------------------------"
#       echo "Fim script boot ;)"
#       echo "------------------------------------------------------"

