# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
#  - before: unalias gp 
  - init: unalias gp
    
  - name: Config 
    command: unalias gp
    openMode: split-right


# - name: Running yarn installs
#   command: cd meu-portal-tchauzinho && yarn  
#   openMode: split-right

# - name: Set custom theme
#   command: |
#     alias ztheme='(){ export ZSH_THEME="$@" && source $ZSH/oh-my-zsh.sh }'
#     ztheme bira
#   openMode: split-right
# npm install 
# npm run configure-database
    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
  - port: 3030
    onOpen: open-preview

    