tasks:
  - name: First Running boot ;)
    init: >
      cd meu-portal-tchauzinho &&
      yarn --emoji true &&
      cd .. &&
      cd frontend &&
      yarn --emoji true &&

      echo "------------------------------------------------------" &&
      echo "Fim script boot ;)" &&
      echo "------------------------------------------------------" &&

      eval $(command gp env -e) &&

      gp sync-done bundle &&

      clear
    openMode: split-right
    
  - name: npm run dev
    init: gp sync-await bundle # wait for the above 'init' to finish
    command: |
      cd frontend    
      npm run dev

  # - name: npx hardhat node server 
  #   init: gp sync-await bundle # wait for the above 'init' to finish
  #   command: |
  #     cd meu-portal-tchauzinho    
  #     clear    
  #     npx hardhat node          

    
ports:
  - port: 3000
    onOpen: open-preview

  - port: 8545
    onOpen: ignore    

  - port: 443
    onOpen: ignore

  - port: 4443
    onOpen: ignore
    
  - port: 3333
    onOpen: ignore
    
    
#     command: |
#       clear    
#       echo "------------------------------------------------------"
#       pwd
#       echo "------------------------------------------------------"
#       cd meu-portal-tchauzinho
#       yarn --emoji true
#       echo "------------------------------------------------------"
#       echo "Fim script boot ;)"
#       echo "------------------------------------------------------"

