tasks:
  - name: Install
    init: >      
      sudo apt install mc tmux fonts-firacode fonts-powerline -y &&
      sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" &&
      gp sync-done bundle # 'bundle' is an arbitrary name
    openMode: split-right     

  - init: gp sync-await bundle
    command: |
      cd web3dev-Solidity_And_Smart_Contracts
      yarn
    openMode: split-right
      
  - init: gp sync-await bundle
    command: |
      alias ztheme='(){ export ZSH_THEME="$@" && source $ZSH/oh-my-zsh.sh }'
      ztheme bira
      clear
    openMode: split-right
    
ports:
  - port: 3000
    onOpen: ignore
    
  - port: 3333
    onOpen: ignore
